// require('core-js/modules/es6.symbol');
// require('core-js/modules/es6.promise');
// require('core-js/modules/es6.object.define-property');
// require('core-js/modules/es6.object.define-properties');
// require('core-js/modules/es6.object.get-own-property-descriptor');
// require('core-js/modules/es6.object.get-prototype-of');
// require('core-js/modules/es6.object.keys');
// require('core-js/modules/es6.object.assign');
// require('core-js/modules/es6.string.iterator');
// require('core-js/modules/es6.array.iterator');
// require('core-js/modules/es6.string.includes');
// require('core-js/modules/es6.map');
// require('core-js/fn/array/includes');
// require('regenerator-runtime/runtime');
// require('core-js/fn/symbol/async-iterator');
export * from './core';
